backend:
  name: github
  repo: xavier-db/my-site
  branch: main

site_url: https://xavier-db.github.io/my-site

media_folder: "posts/images"
public_folder: "/posts/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image filename", name: "image", widget: "string" }
      - { label: "Caption", name: "caption", widget: "text" }