backend:
  name: github
  repo: xavier-db/my-site
  branch: main

site_url: https://xavier-db.github.io/my-site/

media_folder: "posts/images"
public_folder: "/posts/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"

    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Caption", name: "caption", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }